### ISSUE TITLE
HideElementIf Question

### ISSUE THREAD

**Issue by jsinapayen** [nevakee716/HideElementIf#1]
Question
Lorsque j’arrive sur une page objet processus (mgenprocessus) pour une catégorie = processus, nous avons deux cas de figure : 
•	Si le processus est modélisé (via Casewise Modeler)  l’affichage est OK
•	Si, le processus n’est pas modélisé  l’affichage est KO
o	Affichage du diagramme automatique qui de fait ne fonctionne pas puisqu’il a été paramétré pour une règle de gestion 

Voici un morceau du fichier
{ // cache la tab0 (diagramme) par default
                "action": "changeStyle",
                "style": "display",
                "styleValue": "none",
                "type" : "tab", 
                "id" : "tab0",
            },
            {  // affiche la tab0 (diagramme) si c'est un "Processus","Domaine d'activité" 
                "action": "changeStyle",
                "style": "display",
                "styleValue": "block",
                "type" : "tab", 
                "id" : "tab4",
                "property" : "type",
                "operator"  : "=",
                "value" : ["Processus","Macro-Processus","Activité"]
            },
             { // cache la tab8 (diagramme automatique) par default
                "action": "changeStyle",
                "style": "display",
                "styleValue": "none",
                "type" : "tab", 
                "id" : "tab8",
            },
            {  // affiche la tab8 (diagramme automatique) si c'est une règle de gestion 
                "action": "changeStyle",
                "style": "display",
                "styleValue": "block",
                "type" : "tab", 
                "id" : "tab8",
                "property" : "type",
                "operator"  : "=",
                "value" : "Règle de gestion"
            },

**Comment by nevakee716** [comment]
il faut plutot le faire comme ça

Cache la tab0 de diagramming classique si jamais tu as une règle de gestion
Cache la tab8 de diagramming auto si jamais tu n'es pas une règle de gestion

{ // cache la tab8 si ce n'est pas une règle de gestion
"action": "changeStyle",
"style": "display",
"styleValue": "none",
"type" : "tab",
"id" : "tab8",
"property" : "type",
"operator" : "!=",
"value" : "Règle de gestion"
},
{ // cache la tab0 si c'est une règle de gestion
"action": "changeStyle",
"style": "display",
"styleValue": "block",
"type" : "tab",
"id" : "tab0",
"property" : "type",
"operator" : "=",
"value" : "Règle de gestion"
},
